version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: calli
    targets: [go_first_class]
    mod_timestamp: "{{ .CommitTimestamp }}"
    dir: ./cmd
    binary: calli
    flags:
      - -trimpath
    ldflags:
      - -w -s -X 'github.com/bornholm/calli/internal/build.Version={{ .Version }}'
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  name_template: "v{{ .Version }}"

dockers:
  - id: calli
    ids:
      - calli
    use: docker
    dockerfile: misc/docker/Dockerfile
    image_templates:
      - ghcr.io/{{ tolower ( .Env.REPO_OWNER ) }}/calli:{{ .Version }}
      - ghcr.io/{{ tolower ( .Env.REPO_OWNER ) }}/calli:latest
